[package]
name = "ocrp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
clipboard-win = "5.4.0"
image = "0.24.9"
lazy_static = "1.5.0"
rdev = "0.5.3"

bardecoder = "0.5"

rodio = "0.17"
default-device-sink = "0.1"

async-openai = "0.28.0" # Check for latest version
tokio = { version = "1", features = [
    "full",
] } # Use "full" or "rt-multi-thread", "macros"
tempfile = "3.10.1"
dotenvy = "0.15.7"
tray-item = "0.8.0"
eframe = { version = "0.26", default-features = true }
winit = "0.29"

[build-dependencies]
embed-resource = "2"
ico = "0.3"
