[package]
name = "ocrp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
clipboard-win = "5.4.0"
image = "0.25.6"
lazy_static = "1.5.0"
rdev = "0.5.3"
